version: "3.7"

services:
  system-manager:
    build: .
    volumes:
      - /proc/sysrq-trigger:/sysrq
      - ${HOME}/.ssh/authorized_keys:/rootfs/.ssh/authorized_keys
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s
    ports:
      - 5001:5001


