version: "3.7"

volumes:
  nuvlabox-db:
    driver: local

services:
  management-api:
    build: .
    volumes:
      - /proc/sysrq-trigger:/sysrq
      - ${HOME}/.ssh/authorized_keys:/hostfs/.ssh/authorized_keys
      - nuvlabox-db:/srv/nuvlabox/shared
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production
    restart: on-failure
    environment:
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=False
      - NUVLABOX_SSH_PUB_KEY=${NUVLABOX_SSH_PUB_KEY}
      - HOST_USER=$USER
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s
    ports:
      - 5001:5001


