version: "3.7"

volumes:
  nuvlabox-db:
    driver: local

services:
  management-api:
    build: .
    volumes:
      - /proc/sysrq-trigger:/sysrq
      - ${HOME}/.ssh/:/hostfs/.ssh/
      - nuvlabox-db:/srv/nuvlabox/shared
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production
    restart: always
    environment:
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=False
      - NUVLABOX_SSH_PUB_KEY=${NUVLABOX_SSH_PUB_KEY}
      - HOST_USER=$USER
    ports:
      - 5001:5001


